### ISSUE TITLE
prerolls not visible in plex settings

### ISSUE THREAD

**Issue by thenamelessthing** [chadwpalm/PrerollPlus#6]
Hi, I have configured I think correctly on the prerollsplus side but I don't see anything configured in the bonus section of plex. the field remains empty. Did I forget something?

Thank you!

![image](https://github.com/user-attachments/assets/05048199-98b5-4ece-baf7-3e33d7656554)

![image](https://github.com/user-attachments/assets/488687d5-b119-4c81-92cb-bfff07a6c250)

![image](https://github.com/user-attachments/assets/401485b9-19bd-4e7c-8d3a-565b58922e22)

![image](https://github.com/user-attachments/assets/c8bbcef8-5321-41d5-a6dc-f6ab1ea00c19)

**Comment by chadwpalm** [comment]
If I had to guess, it looks like Preroll Plus is unable to connect to your Plex server to update the Preroll (Bonus) line in the Plex settings.

Since "Location of preroll media" is grayed out, I assume you are running it in Docker? When you click the arrow-circle (in the red circle below), do you see multiple local addresses listed?

![image](https://github.com/user-attachments/assets/3a46eacb-02e5-4993-80f4-0d454236ed15)

Another user was seeing this on their setup: https://github.com/chadwpalm/PrerollPlus/discussions/1#discussioncomment-10642992

That user was running Preroll Plus and Plex on different machines. They were running on TrueNAS Scale, so they were seeing multiple IP's in their list.

Is Preroll Plus and Plex running on the same machine, or on different machines? Are you running Plex in any VM's or an area of the network that Preroll Plus might not see?

 What do the logs show when you:
1. Click the arrow-circle?
2. When you save/update a Sequence? This is one scenario when PR+ tries to save the information to Plex.

Please be sure if you post any screenshots of your logs or IP addresses that you block out any public IP's for safety.

**Comment by thenamelessthing** [comment]
Indeed I'm running plex in docker on the same server than PlexPreRollsPlus.

Here is what I see when I trigger the refresh icon.


![image](https://github.com/user-attachments/assets/25dacab7-c3c0-4e0f-b702-e15259a3f974)

**Comment by chadwpalm** [comment]
Try the 192.168.1.3 address. That is a more typical address for a local network. Click on it and it should autofill the rest of the entries. If you use the pulldown to select a server, you shouldn't need to manually alter the IP, port, or SSL settings.

Also, you should only check mark SSL if you are using one of the [Secure] addresses, otherwise that will also cause an issue. I should probably make that more clear in my documentation. If Preroll Plus is on the same local network as Plex there shouldn't be a need to use SSL anyway, unless you are worried about other people on your local network seeing the packets, or if you are connecting to a Plex network outside your home over the internet.

Once you save the settings, you will need to open your Sequence and resave it (just hit update). That will update the preroll entry on the Plex server.

There are three instances when the preroll entry updates:

1. When you create/update a Sequence or Bucket
2. When you start watching a movie
3. On midnight of the first day of a Sequence schedule

**Comment by thenamelessthing** [comment]
ok it work now. I think the problem is that I had simply planned the sequence to start on Oct. 1, but it's now Oct. 2.  I was already planning for next year...  Thank you!
